
// This file was automatically generated by the Dapper.FastCRUD T4 Template
// Do not make changes directly to this file - edit the template configuration instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `connectRanMaster`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=.;Initial Catalog=RanMaster;Integrated Security=True`
//     Include Views:          `True`


// -----------------------------------------------------------------------------------------
// Failed to read database schema - Cannot open database "RanMaster" requested by the login. The login failed. Login failed for user 'MicrosoftAccount\nguyenhoangduy.1997@outlook.com'.
// -----------------------------------------------------------------------------------------

namespace Entity.RanMaster
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

}

